ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'Teacher';

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "lastSpaceId" TEXT,
  ADD COLUMN IF NOT EXISTS "lastX" INTEGER,
  ADD COLUMN IF NOT EXISTS "lastY" INTEGER;
